### ISSUE TITLE
Убрать реакцию бота на неизвестную команду

### ISSUE THREAD

**Issue by gohabereg** [codex-team/codex.bot.v3#9]
Бот будет откликаться на любую команду для других ботов в чате. Или на любое сообщение, которое начинается со слеша.

Можно попробовать сделать настраиваемым. Например откликаться, только если бот был упомянут в сообщении с командой.

**Comment by n0str** [comment]
Второй вариант нравится мне больше. Поддерживаю.

**Comment by talyguryn** [comment]
Если не упомянуто имя, то на любую команду будет откликаться тот бот, который был вызван последний

**Comment by n0str** [comment]
В любом случае отклик нужно убрать, если имя не указано. Но только на неизвестную команду.
